version: "3"

services:
    node:
        image: node:14.0.0
        user: node
        working_dir: /home/node
        tty: true
        stdin_open: true
        environment:
            NODE_ENV: development
        ports:
            - 9000:9000
        volumes:
            - .:/home/node
